### ISSUE TITLE
only 1 JQL query can be made without redeploying in NodeRED

### ISSUE THREAD

**Issue by symon-skelly** [sbonnick/node-red-nodes#1]
With a functioning JIRA Connection, if a function block preceding the JQL block assigns the msg.query a string that contains an issueKey that exists ("issueKey = QAC-37") and the subflow is activated, the JQL block responds correctly, however upon activating the flow again with any other issueKey, the previous issueKey is used for the 2nd activated flow, the response msg.payload is identical to the first activated flow, even though the msg.query is different.

redeploying the subflow with any change (even just moving a block from one position to another) will cause the next JQL query to respond with the correct data, but any subsequent JQL queries will have the same issue until redeploying again.

![first activation (working)](https://user-images.githubusercontent.com/60613068/118721490-3a879280-b82b-11eb-9961-5b73badde382.png)

![second activation (broken)](https://user-images.githubusercontent.com/60613068/118721486-39eefc00-b82b-11eb-897e-43dbcf9e46c5.png)

**Comment by sbonnick** [comment]
Taking a look at it now.

**Comment by sbonnick** [comment]
This should be fixed now in release: node-red-contrib-jira-streams@0.1.15

**Comment by symon-skelly** [comment]
Hey @sbonnick, Thank you for fixing this, however we were forced to use a different plugin because of this issue and have since completed the project. I'm sure that someone else in the future will appreciate the work you put in. :)
